name: CI

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Linux GCC
            os: ubuntu-24.04

          - name: Linux Clang
            os: ubuntu-24.04
            extra_options: -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++

          - name: macOS Intel
            os: macos-13

          - name: macOS ARM
            os: macos-14

          - name: Windows
            os: windows-2022

    steps:
      - uses: actions/checkout@v4

      - name: Configure
        shell: bash
        run: |
          echo ${{ env.BUILD_TYPE }}
          cmake -S serialport -B build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} ${{ matrix.config.extra_options }}

      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v2
        id: cpu-cores

      - name: Build
        shell: bash
        run: |
          echo ${{ env.BUILD_TYPE }}
          export MAKEFLAGS=--keep-going
          cmake --build build --config ${{ env.BUILD_TYPE }} --parallel ${{ steps.cpu-cores.outputs.count }}

      - name: Test
        shell: bash
        run: |
          echo ${{ env.BUILD_TYPE }}
          if [[ "${{ runner.os }}" == 'Windows' ]]; then
          	./build/${{ env.BUILD_TYPE }}/list_ports
          else
          	./build/list_ports
          fi
