name: Test Python

on:
  push:
    paths-ignore:
      - 'a6r-core/**'
      - 'thirdparty/**'
      # - '**/.gitignore'

jobs:
  build:
    name: Test Python
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Test a6r-bmp.py
        run: |
          ./python/a6r-bmp.py data/capture.bmp
          sudo apt-get install openimageio-tools
          idiff -hardfail 0 data/capture.bmp data/capture_converted.bmp
          rm data/capture_converted.bmp

      - name: Test a6r-prs.py
        run: |
          ./python/a6r-prs.py data/*.prs
          ./python/a6r-prs.py data/*.json

      - name: List Directory
        if: always()
        run: |
          git status
          ls -lR
