name: Test Python

on: [push, pull_request]

jobs:
  build:
    name: Test Python
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Test a6r-bmp.py
        run: |
          ./python/a6r-bmp.py data/capture.bmp
          # sudo apt-get install openimageio-tools
          # idiff -hardfail 0 data/capture.bmp data/capture_converted.bmp

          # sudo apt-get install libfuse2t64
          wget -q https://imagemagick.org/archive/binaries/magick
          chmod +x magick
          export APPIMAGE_EXTRACT_AND_RUN=1
          # ./magick compare -metric AE data/capture.bmp data/capture_converted.bmp null:
          # rm magick data/capture_converted.bmp
          ./magick data/capture.bmp -colors 256  data/capture_256.bmp
          ./magick data/capture.bmp -colors 16  data/capture_16.bmp
          ./magick data/capture.bmp -type Palette data/capture_paletted.bmp
          ./magick data/capture.bmp -depth 24 -type data/capture_24bit.bmp
          ./magick data/capture.bmp -depth 32 -type data/capture_32bit.bmp

      - name: Test a6r-prs.py
        run: |
          ./python/a6r-prs.py data/*.prs
          ./python/a6r-prs.py data/*.json

      - name: List Directory
        if: always()
        run: |
          git status
          ls -lR

      - name: Upload Package
        uses: actions/upload-artifact@v4
        with:
          name: data
          path: data
