name: Test Python

on: [push, pull_request]

jobs:
  build:
    name: Test Python
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5

      - name: Test a6r-bmp.py
        run: |
          ./python/a6r-bmp.py data/capture.bmp

          # wget -q https://imagemagick.org/archive/binaries/magick
          # chmod +x magick
          # export APPIMAGE_EXTRACT_AND_RUN=1
          # ./magick compare -metric AE data/capture.bmp data/capture_converted.bmp null:
          # rm magick data/capture_converted.bmp

      - name: Test a6r-prs.py
        run: |
          ./python/a6r-prs.py data/*.prs
          ./python/a6r-prs.py data/*.json

      - name: Test a6r-rc.py
        run: |
          ./python/a6r-rc.py --help

      - name: List Directory
        if: always()
        run: |
          git status
          ls -lR
